name: CI

# When to run this workflow
on:
  # pr to main branch
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test and Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Run tests with coverage
        run: npm run coverage

      - name: Build project
        run: npm run build
